package ATM_DESIGN.enums;

public enum ATMState {
    IDLE,
    START_TRANSACTION,
    READ_AND_VALIDATE_CARD_DETAILS,
    VALIDATE_CASH_WITHDRAWAL_AMOUNT,
    CASH_DISPENSING,
    EJECT_CARD,
    CLOSE_TRANSACTION
}
